### ISSUE TITLE
use with an existing theme

### ISSUE THREAD

**Issue by cutelittleturtle** [lzane/hexo-light-gallery#1]
Hi, I want to use this gallery plugin on  my hexo blog. But the function seems to OVERLAY with the HEXO default image displaying. 

For example, I included 3 images `img1.jpg img2.jpg img3.jpm` in the post. When the site is served, I did not see a gallery, just 3 individual pictures. But when you click on the picture, you can see the lightgallery zoom-in window overlay with the default zoom-in window.

Is there a way to fix that?

theme: hexo-next, hexo-lanscape

_config.yml: 
`lightgallery:
               # all options comment-out/no plugin`

in post (asset_folder true):
`  <div id="gallery">
`
`    {% asset_img img1.jpg img1 %}
`
`    {% asset_img img2.jpg img2 %}
`
`    {% asset_img img3.jpg img3 %}
`   
` </div>

Check: 
css, script, .js are all present in page's source file.

Result:
no gallery:
![image](https://user-images.githubusercontent.com/31291893/30837185-d2208be6-a228-11e7-8901-fb42aea97139.png)

first layer of zoom-in (default)
![image](https://user-images.githubusercontent.com/31291893/30837189-d61d21d2-a228-11e7-856e-37b07f18e3a3.png)

second layer of zoom-in (lightgallery)
![image](https://user-images.githubusercontent.com/31291893/30837192-d8e51b5e-a228-11e7-81e3-8afcdd30057f.png)

**Comment by lzane** [comment]
你好，可能名字里面的“gallery”误导你了，sorry。

这个插件本身只是封装了[lightgallery](https://github.com/sachinchoolur/lightgallery.js)所以它就是用在preview上面的（点击之后预览，加了插件之后可以在底部有一条缩略图）

我猜你需要的照片墙是类似于这一种[baguetteBox](https://github.com/feimosi/baguetteBox.js), 如果需要可以自己引入一下。

至于你说的有两层overlayer应该是与你原本主题的image preview冲突了。

**Comment by cutelittleturtle** [comment]
@lzane 你好！谢谢你的回复。原来如此，我因为看了原版的[demo](https://sachinchoolur.github.io/lightgallery.js/demos/)，以为照片墙也是这个插件的一部分呢。

那我把这个问题关掉了。

能不能好奇的问一下，在不改变主题代码的情况下可以在layout或post里面直接添加<head></head>部分吗？我试过装原版的插件但在post主体部分include <head>和插件都失败了。

**Comment by lzane** [comment]
@cutelittleturtle “能不能好奇的问一下，在不改变主题代码的情况下可以在layout或post里面直接添加部分吗？我试过装原版的插件但在post主体部分include 和插件都失败了。”

sorry. 没读懂你的问题...

**Comment by cutelittleturtle** [comment]
@lzane 对不起描述得比较失败。。。

是这样，[原版的教程](https://github.com/sachinchoolur/lightgallery.js)要求
1.  add lightgallery.css in the <head> of the document
2. Then include lightgallery.min.js into your document

但hexo如果不修改主题文件(themes/next/)的话，貌似没有办法给<head></head>之间添加信息。更待`scaffolds/post.md`和`source/_posts/`都只能更改<body></body>之间的信息。

所以我想请问一下你的插件是怎么做到修改<head></head>之间的信息的。

**Comment by lzane** [comment]
@cutelittleturtle 抱歉，还是看不懂你想表达的意思。。。

这个插件做的就只是注册一个事件，在Hexo trigger `after_post_render` 这个事件的时候就会调我的call back，然后在callback里面修改原本render的html。 你可以看一下src里面的文件，整个插件很短很短的~

**Comment by cutelittleturtle** [comment]
谢谢你的耐心！原谅我没学过html所以对基本的运行规范和流程一点不了解！谢谢！

**Comment by ShawyerPeng** [comment]
你好~这个插件是直接用`npm install --save hexo-light-gallery`安装后就可用吗？但是我这里好像无效。你在READMEd的Usage中说要安装lightgallery.js，我就又把它下载放到hexo主题文件夹下的`source/js`目录，可还是无效。所以想请教你一下正确的方式应该是什么，谢谢~
