### ISSUE TITLE
请教一下插件如何使用？

### ISSUE THREAD

**Issue by ShawyerPeng** [lzane/hexo-light-gallery#2]
你好，这个插件是直接用`npm install --save hexo-light-gallery`安装后就可用吗？但是我这里好像无效。你在READMEd的Usage中说要安装lightgallery.js，我就又把它下载放到hexo主题文件夹下的`source/js`目录，可还是无效。所以想请教你一下正确的方式应该是什么，谢谢~

**Comment by lzane** [comment]
安装完在`_config.yml`里面添加配置了么？ 

看看是不是这两个链接被墙了
js: 'https://cdn.jsdelivr.net/lightgallery.js/1.0.1/js/lightgallery.min.js',
css: 'https://cdn.jsdelivr.net/lightgallery.js/1.0.1/css/lightgallery.min.css',

如果是的话把它们下载下来，存到自己的服务器上面，然后将url填写在`_config.yml`里面

**Comment by ShawyerPeng** [comment]
我一直用的代理，也没有被墙。站点配置里写的是本地路径没用CDN，还是不行~

![](http://oqcr0rg2c.bkt.clouddn.com/18-3-5/69929851.jpg)

**Comment by lzane** [comment]
你试试看Developer Tool里面有什么错误没有。

btw，如果网站有发布的话，可以给了链接

**Comment by ShawyerPeng** [comment]
我看了一下并没有加载lightgallery的js和css，博客地址：https://bitswild.com/，麻烦啦

**Comment by lzane** [comment]
不好意思，没看到有图片的文章额。
没加载就肯定有问题，不过连报错都没有就可能插件都没生效

正常都是直接安装这个插件就可以直接生效的了，请问有没有源码什么的可以放出来好让大家一起debug，不然现在似乎看不出是什么问题

**Comment by ShawyerPeng** [comment]
不知道为什么今天莫名其妙的就就好了2333，难道是浏览器缓存导致没有生效吗......谢谢你啦

**Comment by lzane** [comment]
哈哈哈 调试的时候记得把disable cache勾上

那应该没什么问题了，我关闭issue咯
